apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/fs.yaml
- cnp.yaml
- httproutes/fs.yaml
- pvcs/apps-rustfs.yaml
- pvs/apps-rustfs.yaml
- services/cluster-ip.yaml
- stateful.yaml

