apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-svh
  namespace: self-made
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: "/var/mnt/apps/svh"

