apiVersion: v1
kind: Service
metadata:
  name: coredu
  namespace: self-made
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  selector:
    app: coredu
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP

