apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-rustfs
  namespace: default
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  hostPath:
    path: "/var/mnt/apps/rustfs"

