apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-redis
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: apps-redis

