apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium
  - name: tetragon
  - name: gateway
  - name: cert-manager
  - name: kube-prometheus-stack
  interval: 15m0s
  path: ./flux/monitoring/prometheus
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-cluster

