apiVersion: v1
kind: ConfigMap
metadata:
  name: opendkim
  namespace: default
data:
  opendkim.conf: |
    Syslog yes
    SyslogSuccess yes

    Mode sv
    Canonicalization relaxed/relaxed
    Socket local:/run/opendkim.sock
    PidFile /run/opendkim.pid
    TemporaryDirectory /tmp
    OversignHeaders From
    AutoRestart yes
    AutoRestartRate 10/1h

    KeyTable /etc/opendkim/KeyTable
    SigningTable /etc/opendkim/SigningTable
    InternalHosts /etc/opendkim/InternalHosts

  InternalHosts: |
    127.0.0.1
    localhost
    10.0.0.0/8

  KeyTable: |
    mail._domainkey.${DOMAIN} ${DOMAIN}:mail:/etc/opendkim/keys/mail.private

  SigningTable: |
    *@${DOMAIN} mail._domainkey.${DOMAIN}

