apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/mail.yaml
- cnp.yaml
- configmaps/opendkim.yaml
- configmaps/postfix.yaml
- deployment.yaml
- services/cluster-ip.yaml

