apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-svh
  namespace: self-made
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: apps-svh

