apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/video-api.yaml
- certificates/video-auth.yaml
- certificates/video-media.yaml
- certificates/video.yaml
- cnp.yaml
- configmaps/default.conf.yaml
- deployment.yaml
- httproutes/video-api.yaml
- httproutes/video-auth.yaml
- httproutes/video-media.yaml
- httproutes/video.yaml
- pvcs/apps-svh.yaml
- pvs/apps-svh.yaml
- services/cluster-ip.yaml

