apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prom
  namespace: kube-system
spec:
  secretName: prom-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - prom.${DOMAIN}

