apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-redis
  namespace: default
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/var/mnt/apps/redis"

