apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: video-auth
  namespace: self-made
spec:
  parentRefs:
  - name: public
    namespace: kube-system
    sectionName: video-auth
  hostnames:
  - auth.video.${DOMAIN}
  rules:
  - backendRefs:
    - name: yaoae
      port: 8080

