apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: mikrotik
  namespace: kube-system
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: PodCIDR
  - advertisementType: Service
    service:
      addresses:
      - LoadBalancerIP
    selector:
      matchLabels: {}

