apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth
  namespace: kube-system
spec:
  secretName: auth-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - auth.${DOMAIN}

