apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-helm-release
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium
  - name: tetragon
  - name: gateway
  interval: 15m0s
  path: ./flux/cert-manager/cert-manager/helm
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium
  - name: tetragon
  - name: gateway
  - name: cert-manager-helm-release
  interval: 15m0s
  path: ./flux/cert-manager/cert-manager
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-cluster

