apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-rustfs
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: apps-rustfs

