apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/learn-api.yaml
- certificates/learn-auth.yaml
- certificates/learn-media.yaml
- certificates/learn.yaml
- cnp.yaml
- configmaps/default.conf.yaml
- deployment.yaml
- httproutes/learn-api.yaml
- httproutes/learn-auth.yaml
- httproutes/learn-media.yaml
- httproutes/learn.yaml
- services/cluster-ip.yaml

