apiVersion: v1
kind: ConfigMap
metadata:
  name: coredu-nginx
  namespace: self-made
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name learn.${DOMAIN};
      root /var/www/html/default;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /health {
        return 200;
      }
    }

    server {
      listen 80;
      listen [::]:80;
      server_name media.learn.${DOMAIN};
      root /var/www/html/media;

      location / {
        try_files $uri =404;

        limit_rate 500k;
      }
    }

