apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium
  - name: tetragon
  interval: 15m0s
  path: ./flux/default/postgres
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-cluster

