apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fs
  namespace: kube-system
spec:
  secretName: fs-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - fs.${DOMAIN}

